### ISSUE TITLE
OAuth 2 Server - Token revocation

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#110]
As per http://tools.ietf.org/html/draft-ietf-oauth-revocation-05

Is not really a grant type and likely better served as a self sustained endpoint. Worth investigating spec maturity before implementing.

**Comment by LennyLip** [comment]
[RFC7009 says](https://tools.ietf.org/html/rfc7009#section-2.1)

[...] If the particular token is a refresh token [...] then the authorization server SHOULD also invalidate all access tokens. If the token passed to the request is an access token, the server MAY revoke the respective refresh token as well.

Now, OAuth 2 Server not  "also invalidate all access tokens", when i send a refresh token.

**Comment by LennyLip** [comment]
Also, we not always need 
https://github.com/idan/oauthlib/blob/62ee76f22e8b0a53b2eda4a88e2891ed6578083b/oauthlib/oauth2/rfc6749/endpoints/revocation.py#L123
client authifiaction.

https://tools.ietf.org/html/rfc7009#section-2.1
" The authorization server first validates the client credentials (in
case of a confidential client) and then verifies whether the token
was issued to the client making the revocation request."

if i have public application, we should skip "authenticate_client".

**Comment by thedrow** [comment]
@ib-lundgren Can you describe the changes between your implementation and RFC 7009?

**Comment by JonathanHuot** [comment]
Token Revocation RFC#7009 has been fully implemented, and public endpoints mentionned by @LennyLip has been implemented since 2.0.3.

Check it out latest version at https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/endpoints/revocation.py#L123-L129 done by the commits https://github.com/oauthlib/oauthlib/commit/8b0c466084e4f901f37ae310f3f19c4034a4c29b and https://github.com/oauthlib/oauthlib/commit/bf2f9dbff3e04addd16ad825e6dae30537677afc
