### ISSUE TITLE
`parse_authorization_code_response` has no error checking

### ISSUE THREAD

**Issue by chadwhitacre** [oauthlib/oauthlib#290]
Over at https://github.com/gratipay/gratipay.com/issues/2870 we're finding that [`parse_authorization_code_response`](https://github.com/idan/oauthlib/blob/04631866c058defb480462db1ec13cb7f88780a9/oauthlib/oauth2/rfc6749/parameters.py#L179-L229) sometimes receives an error response that it's [not prepared to handle](https://github.com/idan/oauthlib/blob/04631866c058defb480462db1ec13cb7f88780a9/oauthlib/oauth2/rfc6749/parameters.py#L221-L223). Here's a couple examples of the querystrings we're seeing from different providers:

```
Google:   error=access_denied&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Facebook: error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Should a check for `error` be added, with a call to [`raise_from_error`](https://github.com/idan/oauthlib/blob/04631866c058defb480462db1ec13cb7f88780a9/oauthlib/oauth2/rfc6749/errors.py#L249-L259) (but cf. #2869)?

**Comment by MrkGrgsn** [comment]
I've just encountered this problem with `parse_authorization_code_response` while working on a client.  I can prepare a fix however the error checking must happen before the authorization code is checked (otherwise clients will just continue to receive a `MissingCodeError`), which will be a breaking change because clients' error handling will have to move from this pattern:
```python
try:
    parse_authorization_code_response()
except MissingCodeError:
    # check the error params and handle errors
```
to this one
```python
try:
    parse_authorization_code_response()
except MissingCodeError:
    ...
except AccessDeniedError:
    ...
except etc
```
Clients that don't update will encounter unexpected and unhandled exceptions. I can't see any way to get around this.
