### ISSUE TITLE
SEO improvement

### ISSUE THREAD

**Issue by foxx** [oauthlib/oauthlib#348]
Currently, searching for "python oauth2" doesn't show up on the first 5 pages of Google. I only came across this wonderful project after reading another obscure article from 2012, mentioning that this project was still in beta. Amusingly, the pypi package for this library is the first result for "python oauth", though it would be better if it was the Github page.

In an attempt to reach more developers via Google, I'd like to propose the following;
- Rename repo to "python-oauthlib"
- Modify README to include "Python" in the headers and text
- Modify README to include "oauth2" in the text

Thoughts?

**Comment by foxx** [comment]
@ib-lundgren Are you yay or nay on this one? I can easily put together a PR for this, but it will require someone with ownership to setup redirects and such.

**Comment by ib-lundgren** [comment]
@foxx making us easier to find would be awesome :) I'm all for improving the README. Will need to think about renaming the repo a bit tho.

I quite like what the requests crew did with docs.python-requests.org. Maybe we can do something similar? Aim to have readthedocs be the main landing site but with obvious links to the github page. It would require rebranding https://oauthlib.readthedocs.org/en/latest/ to be more than just a random docs dump of course.

I already own oauthlib.com/org since before but went ahead and registered python-oauth.com/org, python-oauth2.com/org as well as python-oauthlib.com/org. Happy to point them wherever but maybe aim to just promote one of them? Not sure which one :)

**Comment by JonathanHuot** [comment]
Renaming the repository is a no-go for me, and SEO can live with it.
Others points have been already integrated, or added in #575.

Feel free to review and comments.
