### ISSUE TITLE
Build Passing Green when Build not found?

### ISSUE THREAD

**Issue by duaneking** [oauthlib/oauthlib#524]
I'm noticing that when I go to some PR/CR pages that the build page us still using one that cant be found.. but GitHub seems to be saying its all green, anyway.

This is bad.

I'm opening this to track the Build issue that may be blocking other CR's so we can reference it in them, since we cant release anything until our build works 100%.  It could be as simple as people updating their CR's/PR's, but either way its best we explicitly track this.

**Comment by JonathanHuot** [comment]
I believe that since the issues have been created when idan/oauthlib was used, travis-ci succeeded at this time, but it points to an old project which does no longer exists.

Maybe we should trigger a new build for each PR with taking new baseline into account ? 
Either it's doable from the Travis-CI interface itself, or either we ask all PR's owner to change the baseline.

Any other ideas ?

**Comment by duaneking** [comment]
Yes, let the build fail if it should, thats what its there for after all.  Its our canary in this coal mine of RFC's. :)

**Comment by JonathanHuot** [comment]
I have restarted the Travis-CI build for every **open** PRs (it's doable from the Travis's PR tab) prior to the migration date (from 475 until 508). They are all green, except the two oldest PRs:

#387 and #475 are failing, their baseline are too old and contains incompatibility with the building system. Their baselines have to be updated.

**Comment by duaneking** [comment]
Good, going to update both of them now so the authors know.

**Comment by JonathanHuot** [comment]
We have no longer any open PRs
