### ISSUE TITLE
WWW-Authenticate response adds wrong format with comma

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#676]
**Describe the bug**

Since 3.0.0 oauthlib returns 401 with WWW-Authenticate HTTP header. The field is currently not defining the `realm=` option, but it looks OK for the [Bearer Token RFC](https://tools.ietf.org/html/rfc6750#section-3). However, I didn't find any concrete examples of syntax when realm is not present, and if we have to add a comma or not.

Example it's either:
`WWW-Authenticate: Bearer, error=access_denied, error_description=foobar`
or
`WWW-Authenticate: Bearer error=access_denied, error_description=foobar`

In 3.0.x, we are sending the former WITH the comma after `Bearer`.

**How to reproduce**

Execute `raise errors.InvalidTokenError()` in your RequestValidator.

**Expected behavior**

I saw a couple of providers which are sending a comma after the `Bearer` keyword. I think we must do the same.

**Additional context**

Please provide any further context here.

- Using server code with `bottle-oauthlib` declaring a OAuth2 ResourceServer

**Comment by Abhishek8394** [comment]
1. There should not be a comma **immediately after** `Bearer` as that is incomplete. `Bearer` expects some more data like; `realm` for example. Below is an example from [RFC 6750 section 3 Intro end](https://tools.ietf.org/html/rfc6750#section-3).
```
HTTP/1.1 401 Unauthorized
     WWW-Authenticate: Bearer realm="example",
                       error="invalid_token",
                       error_description="The access token expired"
```

2. `realm` is optional, given you use some other option. As per [RFC 2617 Section 3.2.1](https://tools.ietf.org/html/rfc2617#section-3.2.1) the first field so to speak is `<challenge-name> <challenge>`.  
So we can have `Bearer nonce="somenonce"` instead of `realm`. But something has to be there, it cannot be blank.

**Comment by JonathanHuot** [comment]
So basically it means that the preferred approach would be to add the `realm` (or any other "challenge") as a parameter of the oauthlib Server/Endpoint ?
I think it makes sense.

**Comment by Abhishek8394** [comment]
Yes, a challenge must be added. It would be nice if challenge is
configurable and has hooks, for composing challenges and verifying them.

**Comment by freeman1981** [comment]
Hello!
Sorry for my English (google translate helps me). 
I use [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit) as an authorization server, and [mozilla-django-oidc](https://github.com/mozilla/mozilla-django-oidc) as a client and resource server. 

The client crashes because of the "Barrier," (coma after Barrier) - I had to make a crutch in the client - something like 
`headers ['www-authenticate'] = headers ['www-authenticate']. Replace ('Bearer,', 'Bearer', 1)`. 

Looked specs nowhere did I see a comma as mentioned by @Abhishek8394. Additionally looked [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate).

I suggest removing the comma after the Barrier.

**Comment by Abhishek8394** [comment]
The comma here is a delimiter. I mentioned that it should *not* be
`Bearer,` but `Bearer key=value` and then comma if more key value pairs
need to be added.
The client should not send `Bearer,` either. Does it fail for you if you
use the correct form?

**Comment by Abhishek8394** [comment]
The comma here is a delimiter. I mentioned that it should *not* be
`Bearer,` but `Bearer key=value` and then comma if more key value pairs
need to be added.
The client should not send `Bearer,` either. Does it fail for you if you
use the correct form?

**Comment by freeman1981** [comment]
If I use correct form - everythink OK) As I mentioned before I use crutch `headers ['www-authenticate'] = headers ['www-authenticate']. Replace ('Bearer,', 'Bearer', 1)` ))

For example `Bearer, foo=bar, spam="egg"` become in my client (mozila-django-oidc) `Bearer foo=bar, spam="egg"`

I have some questions for mozila-django-oidc - but its another story)

**Comment by auvipy** [comment]
ok
