### ISSUE TITLE
Issues in constructing the OAuth2Session with scope

### ISSUE THREAD

**Issue by mmotahar-ia** [oauthlib/oauthlib#701]
**Describe the bug**
When preparing an Oauth 2.0 request that includes scope, As per the the following link, We should be able to pass the scope 

https://requests-oauthlib.readthedocs.io/en/latest/api.html#requests_oauthlib.OAuth2Session

`classrequests_oauthlib.OAuth2Session(client_id=None, client=None, auto_refresh_url=None, auto_refresh_kwargs=None, **scope=None**, redirect_uri=None, token=None, state=None, token_updater=None, **kwargs)`

However, when we create scope using either of the following format 
scope = ['openid','IdentityAPI']
scope = "openid IdentityAPI"
scope = ['openid IdentityAPI']

and pass it to the request_for_token we get the following error in Python terminal

`oauthlib.oauth2.rfc6749.errors.InvalidScopeError: (invalid_scope)`

And below is the output in our server logs.

`w3wp.exe Information: 0 : 2019-09-09 11:38:50.118 +08:00 [Information] Start token request
2019-09-09 11:38:50.119 +08:00 [Debug] Start client validation
2019-09-09 11:38:50.119 +08:00 [Debug] Start parsing Basic Authentication secret
2019-09-09 11:38:50.119 +08:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
w3wp.exe Information: 0 : 2019-09-09 11:38:50.119 +08:00 [Information] Secret id found: "my_id"
2019-09-09 11:38:50.124 +08:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
w3wp.exe Information: 0 : 2019-09-09 11:38:50.124 +08:00 [Information] Client validation success
w3wp.exe Information: 0 : 2019-09-09 11:38:50.124 +08:00 [Information] Start token request validation
w3wp.exe Information: 0 : 2019-09-09 11:38:50.125 +08:00 [Information] Start password token request validation
w3wp.exe Warning: 0 : 2019-09-09 11:38:50.125 +08:00 [Warning] Scopes missing or too long
w3wp.exe Error: 0 : 2019-09-09 11:38:50.125 +08:00 [Error] Invalid scopes.
 {
  "ClientId": "my_id",
  "ClientName": "My Client Name",
  "GrantType": "password",
  "Raw": {
    "grant_type": "password",
    "username": "my_username",
    "password": "******"
  }
}
w3wp.exe Information: 0 : 2019-09-09 11:38:50.125 +08:00 [Information] End token request
`

**How to reproduce**

Steps to reproduce the behavior.

Open the python terminal and run below commands following this documentation. 

import requests
import requests_oauthlib
from requests_oauthlib import OAuth2Session

client_id = 'my_id'
client_secret = 'my_secret'

username = "my_username"
password = "Mypassword"
base_url = "https://our_indetity_server.com"
token_url = base_url + "/identity/connect/token"
my_scope = ['openid','IdentityAPI']
oauth = OAuth2Session(client=LegacyApplicationClient(client_id=client_id),scope=my_scope)
token = oauth.fetch_token(token_url=token_url,username=username, password=password, client_id=client_id, client_secret=client_secret)

**Expected behavior**

A description of what you expected to happen.

**Additional context**

Please provide any further context here.

- Are you using OAuth1, OAuth2 or OIDC?
- Are you writing client or server side code?
- If client, what provider are you connecting to?
- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...?

**Comment by JonathanHuot** [comment]
Hi @mmotahar-ia, it seems related to the requests-oauthlib's fetch_token function which does not use the scope. It works for WebApplication because the "scope" is passed into the authorization request and not in the fetch_token. However, as you mentioned, it does not work for LegacyApplication and the same function is used for BackendApplication.

An issue and PR has already been discussed in the requests-oauthlib at https://github.com/requests/requests-oauthlib/pull/283, however it didn't completed because of the lack of tests/changelog. I think it can be reopened because it seems a outstanding issue to me. If you have time to create a PR on requests-oauthlib referencing the old one, that would be a great help to the community.

Still, the immediate workaround is to add the "scope" to the fetch_token function instead of the OAuth2Session.

I'm closing the issue because it does not belongs to oauthlib itself, but to requests-oauthlib.
